language: go

go:
  - 1.12.x

services:
  - docker

cache:
  directories:
  - $GOPATH/pkg/dep

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - ci/start-okd-4.0.0.sh

after_failure:
  - docker ps -a
  - for log in $(docker ps -qa | xargs); do docker logs --tail 500 $log; done

script:
  - make build
  - make test-e2e-16 KUBECONFIG=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/admin.kubeconfig
  - make test-e2e-17 KUBECONFIG=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/admin.kubeconfig
