language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

services:
  - docker

cache:
  directories:
  - $GOPATH/pkg

before_script:
  - ci/start-okd-4.0.0.sh

after_failure:
  - docker ps -a
  - for log in $(docker ps -qa | xargs); do docker logs --tail 500 $log; done

script:
  - export IMAGE="jmesnil/wildfly-operator"
  - export TAG="CI_${TRAVIS_BUILD_NUMBER}"
  - make image
  - oc import-image quay.io/${IMAGE}/${TAG}
  - make setup
  - make test-e2e-16 KUBECONFIG=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/admin.kubeconfig
  - make test-e2e-17 KUBECONFIG=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/admin.kubeconfig