apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: quickstart
spec:
  applicationImage: "quay.io/jmesnil/wildfly-operator-quickstart:17.0"
  size: 3
  sessionAffinity: false
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 3Gi
