apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wildfly-operator
rules:
  - apiGroups:
      - wildfly.org
    resources:
      - "*"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - wildfly.org
    resources:
      - schemas/status
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wildfly-operator
  namespace: wildfly-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wildfly-operator
subjects:
  - kind: ServiceAccount
    name: wildfly-operator
    namespace: wildfly-operator
roleRef:
  kind: ClusterRole
  name: wildfly-operator
  apiGroup: rbac.authorization.k8s.io