apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wildflyservers.wildfly.org
spec:
  group: wildfly.org
  names:
    kind: WildFlyServer
    listKind: WildFlyServerList
    plural: wildflyservers
    shortNames:
      - wfly
    singular: wildflyserver
  versions:
    - name: v1beta1
      served: true
      storage: true
  scope: Namespaced
