apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wildflyservers.wildfly.org
spec:
  group: wildfly.org
  names:
    kind: WildFlyServer
    listKind: WildFlyServerList
    plural: wildflyservers
    shortNames:
      - wfly
    singular: wildflyserver
    scope: Namespaced
  version: v1beta1
  scope: Namespaced
