= WildFly Operator - User Documentation
:toc:               left

This guide documents the various features and capabilites provides by the WildFly Operator.

This guide is complemented by the link:../apis.adoc[API Documentation].

[[basic-install]]
# Basic Install (Phase I)

The features and capabilities of **Basic Install (Phase I)** deals with the provisioning, installation and configuration of a Java application managed by the WildFly Operator.

[[application-image]]
## Specify the Docker Application Image

The `applicationImage` specifies the Docker application image that contains the Java application.
The operator support two kind of application images:

    * WildFly S2I Builder/Runtime application image. This application image is built by using https://github.com/wildfly/wildfly-s2i[WildFly S2I]. This is the default one.

[source,yaml]
.Example of application image configuration
----
spec:
  applicationImage: "quay.io/wildfly-quickstarts/wildfly-operator-quickstart:18.0"
----

The `applicationImage` accepts different references to Docker image:

* the name of the image: `quay.io/wildfly-quickstarts/wildfly-operator-quickstart`
* a tag: `quay.io/wildfly-quickstarts/wildfly-operator-quickstart:18.0`
* a digest: `quay.io/wildfly-quickstarts/wildfly-operator-quickstart@sha256:0af38bc38be93116b6a1d86a9c78bd14cd527121970899d719baf78e5dc7bfd2`
* an imagestream tag: `wildfly-operator-quickstart:latest`

[NOTE]
====
Using an imatestream tag is supported only on OpenShift and the imagestream must be in the same namespace that the deployed `WildFlyServer` resource.
The WildFly Operator will trigger new deployment of the application whenever the image corresponding to the imagestream tag changes.
====

[[size]]
## Specify the Size of the Application

The `replicas` specifies the size of the application, i.e. the number of pods that runs the application image.

[source,yaml]
.Example of size configuration
----
spec:
  replicas:2
----